### ISSUE TITLE
"Empty or outdated config file. Please run ‘config activate’ and retry" while upgrading on OS X El Capitan

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-node-client#161]
## Problem

The installer fails when upgrading from Prey 1.4.1 or older. The title is the actual problem.

When running the `config activate` command you get this output,

![screen 20shot 202015-10-20 20at 2005 24 00](https://cloud.githubusercontent.com/assets/401279/10641861/6ed6eae8-77f1-11e5-94be-34982e196538.png)

## How it was detected

Tons of user feedback.

## Suggested solution

Fix the upgrading process.

## More info

- https://trello.com/c/boAd5xaD
- https://app.intercom.io/a/apps/aftzp1os/inbox/unassigned/conversations/1411593280

**Comment by markdrayton247** [comment]
there is none.

**Comment by lemavri** [comment]
In that case, could you please run the following commands and see if you can complete the configuration process?

`sudo cp /usr/local/lib/prey/versions/1.4.2/prey.conf.default /etc/prey/prey.conf`
`sudo chown prey:wheel /etc/prey/conf`
`sudo /usr/local/lib/prey/versions/1.4.2/bin/prey config gui` (It takes a few seconds to load the gui).

**Comment by markdrayton247** [comment]
yes that works, thanks
2nd line should be: sudo chown prey:wheel /etc/prey/prey.conf
(however i still can't locate the device, which is why i tried reinstalling..)

**Comment by lemavri** [comment]
Thanks, I fixed my previous comment.

What is the `/var/log/prey.log` file showing?

**Comment by markdrayton247** [comment]
nothing, empty

**Comment by lemavri** [comment]
What about `ps aux | grep prx`?

If the previous command returns nothing, then try the following: `sudo launchctl load /Library/LaunchDaemons/com.prey.agent.plist` and check the config file again.

**Comment by markdrayton247** [comment]
/Library/LaunchDaemons/com.prey.agent.plist: No such file or directory

**Comment by lemavri** [comment]
Ok, so let's try running the post_install hooks: `sudo /usr/local/lib/prey/versions/1.4.2/bin/prey config hooks post_install`, and then try again to load the agent plist.

Thanks for your patience, by the way.

**Comment by markdrayton247** [comment]
Running "config activate" as prey
--
Error running command: spawn EACCES
--
 -- This is probably because the new `prey` user does not have
 -- read and exec access to the full path: /usr/local/lib/prey/versions/1.4.2/bin
Error! Command failed: 

plist still no such file... thanks for helping

**Comment by lemavri** [comment]
Ok, so let's ensure the `prey` user does have access to the full path, with the following command:

`sudo chown -R prey:wheel /usr/local/lib/prey`

and then re-run the `sudo /usr/local/lib/prey/versions/1.4.2/bin/prey config hooks post_install` command.

**Comment by markdrayton247** [comment]
Running "config activate" as prey
--
Error running command: spawn EACCES
--
 -- This is probably because the new `prey` user does not have
 -- read and exec access to the full path: /usr/local/lib/prey/versions/1.4.2/bin
Error! Command failed:

**Comment by lemavri** [comment]
That's really weird. I'll have to give it a closer look and get back to you later.

**Comment by lemavri** [comment]
@markdrayton247 In a brief moment of brightness I came up with an idea. Could you please try running this? `sudo -u prey ls -al /usr/local/lib/prey`

**Comment by markdrayton247** [comment]
ls: /usr/local/lib/prey: Permission denied

(yes I did sudo)

**Comment by lemavri** [comment]
Ok, that was the intended output.

Could you please try running these: 

`sudo chown $(whoami):admin /usr/local/`
`sudo chown $(whoami):admin /usr/local/lib`
`sudo /usr/local/lib/prey/versions/1.4.2/bin/prey config hooks post_install`

**Comment by markdrayton247** [comment]
ends with:

Running "config activate" as prey

--

Error running command: spawn EACCES

--

 -- This is probably because the new `prey` user does not have

 -- read and exec access to the full path:
/usr/local/lib/prey/versions/1.4.2/bin

Error! Command failed:

**Comment by lemavri** [comment]
Does it end with error this time? If not, could you check if there's a .plist now?

`sudo launchctl load /Library/LaunchDaemons/com.prey.agent.plist`

**Comment by markdrayton247** [comment]
yes, no plist exists. error is :
Error running command: spawn EACCES
--
 -- This is probably because the new `prey` user does not have
 -- read and exec access to the full path: /usr/local/lib/prey/versions/1.4.2/bin
Error! Command failed:

**Comment by lemavri** [comment]
Perhaps it's a problem with the Prey user, what happens if you run this:

`sudo /usr/local/lib/prey/versions/1.4.2/lib/conf/tasks/utils/create_user.sh prey`

**Comment by lemavri** [comment]
Also, could you please re-check what are the permissions for the following folders:

`ls -al /usr/ | grep local`
`ls -al /usr/local | grep lib`
`ls -al /usr/local/lib | grep prey`

**Comment by markdrayton247** [comment]
the create_user script gives:
prey user already exists!
prey already seems to have impersonation privileges. Skipping...
---
drwxr-xr-x     8 markdrayton  admin    272  4 Nov 11:46 local
drwx------   4 markdrayton  admin  136 16 Nov 20:16 lib
drwxr-xr-x  3 prey         wheel  102 16 Nov 20:16 prey

**Comment by lemavri** [comment]
Could you please run `sudo chmod 755 /usr/local/lib` and then retry `sudo /usr/local/lib/prey/versions/1.4.2/bin/prey config hooks post_install`?

**Comment by markdrayton247** [comment]
now we're getting somewhere :

Running post_activate hooks...

Voila! All good.

--

Installing init scripts.

Sweet! Please run `prey config gui` to finish installation.

Voila! All good.

**Comment by markdrayton247** [comment]
ran the gui, all seems cool now, preyproject can connect to this machine.

I'm not sure how I got into such a mess, but you are a patient and very
helpful man. thank you sir.

**Comment by lemavri** [comment]
On the contrary; you sir are the hero, thank **you**. This helped me identify an edge case which caused this issue. Now I'll be able to fix it in our next release.

**Comment by sevenlayercookie** [comment]
Just wanted to say that I had this problem also with 1.4.2 on El Capitan, installing Prey for the first time ever. I followed your instructions in the last few posts and it fixed my problems. Thanks!

**Comment by Monochrome001** [comment]
Hi everyone,

Could it possible for one of you to do "beginner" tutorial for that operation ? I'm also on El Capitan, I've got the same problem, but I'm lost with these instructions, even if I understood that all of that are commands to input in Terminal.

Thank you all

**Comment by lemavri** [comment]
Hello @Monochrome001, I'll be releasing 1.5.0 on Wednesday and the OS X installer will include the extra permissions instruction needed for El Capitan.

**Comment by Monochrome001** [comment]
Thank you !

**Comment by lemavri** [comment]
This issue is fixed in the Prey v1.5.0 Mac OS X installer being released in a few minutes.

**Comment by kraftykaela** [comment]
I have installed Prey v1.5.0 on El Capitan and I still get the same "Empty or outdated config file. Please run 'config activate' and retry." when trying to log in (see attached screenshot).
![screen shot 2016-02-04 at 6 47 58 pm](https://cloud.githubusercontent.com/assets/17075495/12834791/fbd8d3a8-cb6f-11e5-957f-55406769afc7.png)

**Comment by jonwreed** [comment]
It would be great if this could be fixed, I am NOT entering sudo commands on my machine. But if this can ever be fixed by uninstalling and reinstalling let us know. Thx.

**Comment by tonsequitur** [comment]
I am having the same issue and need some clearer instructions too please.
After installing, I try to sign in with my existing account and get: 
"Empty or outdated config file. Please run 'config activate' and retry."

I was able to install on my macbook OK: Yosemite 10.10.1
However, I am getting this error on my iMac: Yosemite 10.10.5

**Comment by tonsequitur** [comment]
followup: There was a permission issue for sudo so that Prey could not write to the system files. I couldn't fix the sudo permission problem so I upgraded to El Capitan and then the install worked fine.

**Comment by jonwreed** [comment]
For the record being on El Capitan doesn't necessarily solve this problem. It's a serious open issue and in my case is happening on El Capitan Therefore the laptop I use the most and pay for is not protected by Prey. I hope this can be fixed in an updated release soon. Thanks.

**Comment by cyaconi** [comment]
Nice discovery @tonsequitur, prey user should have permission to access the config file once the installation ends. 
@jonwreed Can you share the content of file /etc/sudoers.d/50_prey_switcher, if exists?

**Comment by javo** [comment]
Hello @tonsequitur and @jonwreed 
I believe I've found the cause of this issue but I need some confirmation. Could you check you perrmissions for the following folders please:
`ls -al /usr/ | grep local`
`ls -al /usr/local | grep lib`
`ls -al /usr/local/lib | grep prey`

Thanks!

**Comment by escapone** [comment]
it is impossible to install EL CAPITAN mac on prey, it sais outdated config file all time. Anyone a solution?

**Comment by javo** [comment]
Hello @escapone, 
We now got this issue covered but the fix is gonna be available in the next release (1.6.2).
For now please run this command: `sudo chmod -R 755 /usr/local` and then retry the installation.
Please let me know how it went :)

**Comment by escapone** [comment]
GREAT! Works like a charm!

**Comment by deeplypuzzled** [comment]
Just to confirm that I have had the same probem on 1.6.1 and lemavri's/javo's fix (I assume the chmod) fixed it for me. Many thanks.

**Comment by jonwreed** [comment]
Is the 1.6.2 release where this issue is fixed out yet? If not, any idea of timeframe? Thank you.

**Comment by javo** [comment]
Hi @deeplypuzzled and @jonwreed,

Thanks for your comments, the new release with the fix for this issue is gonna be released this week. We're gonna let you know as soon as it's available.

**Comment by javo** [comment]
The new release 1.6.2 is now available with the fix to this issue :)

**Comment by jonwreed** [comment]
Thanks - the new release solved the issue for me. Took a while but appreciate you handling this, very happy my most important laptop now back online. Thx.
