### ISSUE TITLE
Suport bunsenLabs linux

### ISSUE THREAD

**Issue by mef** [prey/prey-node-client#355]
Hi,

The setup of Prey fails on bunsenLabs linux distribution (debian derivative), with the following error message: 

> Error! Invalid os: does not exist.

````
$ lsb_release -a
No LSB modules are available.
Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 8.1 (Hydrogen)
Release:	8.1
Codename:	Hydrogen
````

Distro's website: https://www.bunsenlabs.org/

Could you add suport for this distribution, please?

P.S. instead of adding each distro variant individually, it might be worth finding a more generic method to support derivatives:

````
$ cat /etc/os-release
[...]
ID=bunsenlabs
ID_LIKE="debian"
[...]
VERSION_ID="8.1"
````

**Comment by mef** [comment]
Workaround to make prey setup work on unsupported debian derivatives:

1. Install the `.db` package
2. As soon as the config GUI appears, edit the file `/usr/lib/prey/current/node_modules/linus/index.js`: inside the callback function of `lsb_release` (line 43 in current version), replace `return cb(null, res);` by `return cb(null, 'debian');`:
````
var get_distro_info = function(what, lsb_param, issue_cb, cb) {
  lsb_release(lsb_param, function(err, res) {
    if (res && res != '')
      return cb(null, 'debian');
````
3. Proceed with the configuration

**Comment by javo** [comment]
Nice @mef,
We've also added the BunsenLabs distro so it should work now.

**Comment by mef** [comment]
FYI, the problem is still here when installing prey 1.7.4 on bunsenLabs 9.4 (Helium).

````bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 9.4 (Helium)
Release:	9.4
Codename:	helium
````
